name: PR Preview & Testing
on:
  pull_request:
    paths: ['frontend/**']

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Preview
        uses: cloudflare/pages-action@v1
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: e52-reality
          directory: frontend/dist

      - name: Run Visual Tests
        run: |
          npm run test:visual -- --url=${{ steps.deploy.outputs.url }}

      - name: Performance Audit
        run: |
          npx lighthouse ${{ steps.deploy.outputs.url }} --output=html --output-path=./lighthouse-report.html

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed: ${{ steps.deploy.outputs.url }}`
            })
